### ISSUE TITLE
theme did not applied properly, some text got crop from search result

### ISSUE THREAD

**Issue by ahloiscreamo** [rose-pine/vimium-c#1]
![Screenshot from 2023-01-30 22-57-24](https://user-images.githubusercontent.com/9318372/215518937-ccfa42df-99f1-45e0-8337-324867440c65.png)

Hello, i applied the theme and got this. (moon variant)

vimium-c 1.99.97
firefox 109

**Comment by SQLaura** [comment]
try changing the width of `.top` and `.bottom` to 50% and then also change the font-size of `.bottom>a` to something bigger, it should give the look of images in README. Sorry this is probably too late because I just applied theme and same thing happened to me.

**Comment by ahloiscreamo** [comment]
Thanks for the guide, it work flawless !
i will close this issue~
![Screenshot from 2023-09-01 22-58-27](https://github.com/rose-pine/vimium-c/assets/9318372/49844da7-b8af-4c0d-8a12-a26ec7e6996c)
